SHUFFLE_TRIALS: TRUE
N_BACK: 2 # do not repeat words from n last trials

# visual
BACKGROUND_COLOR: grey
TEXT_SIZE: 32

TASK_POS: [0, 200]
TASK_SIZE: 32
TASK_COLOR: black

ANSWERS_POS: [0, -50]
ANSWERS_OFFSET: [100, 0]
ANSWER_SIZE: 32
ANSWER_COLOR: black

SHOW_FRAMES: TRUE
FRAME_LINE: 2
FRAME_COLOR: black
FRAME_COLOR_CORR: green
FRAME_COLOR_WRONG: red

SHOW_IN_TRIAL_INSTRUCTION: TRUE
IN_TRIAL_INSTRUCTION_POS: [0, 300]
IN_TRIAL_INSTRUCTION_SIZE: 32
IN_TRIAL_INSTRUCTION_COLOR: black

INSTRUCTION_SIZE_TRAINING_1: [1600, 1000]
INSTRUCTION_SIZE_TRAINING_2: [1600, 1000]
INSTRUCTION_SIZE_EXPERIMENT: [1600, 1000]

# time
STIM_TIME_TRAINING_1: 9999
STIM_TIME: 5
WAIT_TIME: 2
WAIT_JITTER: [0, 0]

# fixation
FIXATION_SYMBOL: +
FIXATION_COLOR: black
FIXATION_SIZE: 70
FIXATION_POS: [0, 0]
FIXATION_TIME: 0.5

# feedback
FEEDBACK_COLOR: black
FEEDBACK_SIZE: 32
FEEDBACK_POS: [0, -200]

# clock
## show clock n second before trial end
SHOW_CLOCK: -1
CLOCK_POS: [0, 490]
CLOCK_SIZE: 80
SHOW_CLOCK_IN_TRAINING_1: False